#!/usr/bin/env bash
# Generates the bindings for the pmdsky-debug headers.
# Note that bindgen needs to be in the path and pmdsky-debug needs to be checkout out.

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

bindgen \
  --raw-line '//! This module contains the "raw" functions and types from the game. They are generated by bindgen. It is generally recommended to try and use [`crate::api`] instead.' \
  --raw-line "//!" \
  --raw-line "//! For the documentation, see the symbol YAML files of pmdsky-debug at <https://github.com/UsernameFodder/pmdsky-debug/tree/master/symbols>." \
  --raw-line "#![allow(non_upper_case_globals)]" \
  --raw-line "#![allow(non_camel_case_types)]" \
  --raw-line "#![allow(non_snake_case)]" \
  --raw-line "#![allow(clippy::missing_safety_doc)]" \
  --raw-line "#![allow(clippy::useless_transmute)]" \
  --ctypes-prefix "crate::ctypes" \
  --use-core \
  --no-layout-tests \
  --no-derive-copy \
  --no-derive-debug \
  --default-enum-style moduleconsts \
  --newtype-enum ability_id \
  --newtype-enum dungeon_group_id \
  --newtype-enum exclusive_item_effect_id \
  --newtype-enum fixed_room_id \
  --newtype-enum iq_group_id \
  --newtype-enum iq_skill_id \
  --newtype-enum item_id \
  --newtype-enum monster_id \
  --newtype-enum move_id \
  --newtype-enum script_opcode_id \
  --newtype-enum script_var_id \
  --newtype-enum special_process_id \
  --newtype-enum type_id \
  $SCRIPT_DIR/include.h \
  -- \
  -target armv5te-none-eabi \
  > $SCRIPT_DIR/src/ffi.rs
