#pragma once
#include <pmdsky.h>

// These are generated by the `patches!` macro of the eos-rs-proc crate.
extern bool eos_rs_apply_item_effect(struct entity* user, struct entity* target, struct item* item, bool is_thrown);
extern bool eos_rs_apply_move_effect(move_effect_input* data, struct entity* user, struct entity* target, struct move* move);
extern void eos_rs_call_special_process(undefined4* unknown, uint32_t special_process_id, short arg1, short arg2);
