/* !file overlay11 */
/* OpcodeCheck = ?????; unknown */
/* GetParameterCount = ?????; unknown */
/* ScriptEngineReturnTwo = ?????; unknown */

/* !file overlay29 */
/* ApplyMoveEffect = ?????; unknown */
ApplyMoveEffectHookAddr = 0x023302E4;
ApplyMoveEffectJumpAddr = 0x0233310C;
ApplyItemEffectHookAddr = 0x0231C434;
ApplyItemEffectJumpAddr = 0x0231D574;

/* Add your own symbols here... */

/* !file arm9 */
ChangeGlobalBorderColor = 0x02027D74;
