/* !file overlay11 */
OpcodeCheck = 0x022DF474;
GetParameterCount = 0x022DF42C;
ScriptEngineReturnTwo = 0x022E3A98;

/* !file overlay29 */
ApplyMoveEffect = 0x0232FC60;
ApplyMoveEffectHookAddr = 0x02330C98;
ApplyMoveEffectJumpAddr = 0x02333AC0;
ApplyItemEffectHookAddr = 0x0231CEA4;
ApplyItemEffectJumpAddr = 0x0231DFE0;

/* Add your own symbols here... */

/* !file arm9 */
ChangeGlobalBorderColor = 0x02027DE0;
